name: funflow2 CI (Linux, Nix)

on: [push]

jobs:
  build:
    name: funflow2 [build >> tests >> doc]
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v9
        # with:
        #   skip_adding_nixpkgs_channel: true
      - uses: cachix/cachix-action@v6
        with:
          name: tweag-funflow2
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      # Builds
      # docker-client library with its tests
      - name: Build docker-client library
        run: nix-build -A docker-client
      - name: Build docker-client test suite
        run: nix-build -A docker-client-tests -o docker-client-tests
      - name: Run docker-client unit tests
        run: ./docker-client-tests/bin/primary --pattern "unit"
      # Note: these tests take about 10s to run. If executing time
      # gets much longer we can rethink when we want to run these.
      - name: Run docker-client <--> docker integration tests
        run: ./docker-client-tests/bin/primary --pattern "integration"
      # funflow library with its tests
      - name: Build funflow library
        run: nix-build -A funflow
      - name: Build funflow tests
        run: |
          echo Build tests
          TESTS_PATH=$(nix-build -A funflow-tests)
          echo Running tests
          # Funflow tests have to be run in the `funflow` folder, like stack does, in order to have access to test assets
          cd ./funflow
          $TESTS_PATH/bin/test-funflow
          cd ..
      # Build documentation
      - name: Build docs and tutorials
        run: |
          # 1. API Docs
          nix-build -A api-docs -o funflow-docs
          # Need to materialize API documentation symlinks here
          # since the deploy stage below doesn't deep copy
          mkdir -p funflow-docs-materialized/share
          cp -rL ./funflow-docs/share/* ./funflow-docs-materialized/share

          # 2. Documentation index
          nix-build -A doc-index -o result
          cp result/share/index.html ./funflow-docs-materialized/share
          
          # 3. Tutorials
          nix-build -A generate-funflow-tutorials -o result
          result/bin/generate-funflow-tutorial funflow-tutorial/notebooks ./funflow-docs-materialized/share/tutorial
      # Deploy documentation to a github page
      - name: Deploy docs
        # Push to GitHub Pages only on master
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./funflow-docs-materialized/share
